apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-http-echo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: manifests/http-echo
    repoURL: https://github.com/tor-wei/ce10grp2-gitops.git
    targetRevision: main
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
